version: "3.8"
services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
  db:
    container_name: inventory-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
